---
title: "MNIST Example"
author: "Darin Stephenson"
date: "6/7/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
require("knitr")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir=normalizePath("..")) #set working directory to the project directory
library(conflicted)
library(tidyverse)
library(randomForest)
library(keras)
conflict_prefer("select", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("filter", "dplyr")
```

```{r}
# modification of https://gist.github.com/brendano/39760
# automatically obtains data from the web
# creates two data frames, test and train
# labels are stored in the y variables of each data frame
# can easily train many models using formula `y ~ .` syntax

# gunzip the files
#R.utils::gunzip("train-images-idx3-ubyte.gz")
#R.utils::gunzip("train-labels-idx1-ubyte.gz")
#R.utils::gunzip("t10k-images-idx3-ubyte.gz")
#R.utils::gunzip("t10k-labels-idx1-ubyte.gz")#

# helper function for visualization
show_digit = function(arr784, col = gray(12:1 / 12), ...) {
  image(matrix(as.matrix(arr784[-785]), nrow = 28)[, 28:1], col = col, asp=1, ...)
}

# load image files
load_image_file = function(filename) {
  ret = list()
  f = file(filename, 'rb')
  readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  n    = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  nrow = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  ncol = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  x = readBin(f, 'integer', n = n * nrow * ncol, size = 1, signed = FALSE)
  close(f)
  data.frame(matrix(x, ncol = nrow * ncol, byrow = TRUE))
}

# load label files
load_label_file = function(filename) {
  f = file(filename, 'rb')
  readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  n = readBin(f, 'integer', n = 1, size = 4, endian = 'big')
  y = readBin(f, 'integer', n = n, size = 1, signed = FALSE)
  close(f)
  y
}

# load images
train = load_image_file("train-images-idx3-ubyte")
test  = load_image_file("t10k-images-idx3-ubyte")

# load labels
train$y = as.factor(load_label_file("train-labels-idx1-ubyte"))
test$y  = as.factor(load_label_file("t10k-labels-idx1-ubyte"))
```


```{r}
# view test image
i <- 651
show_digit(train[i, ])
print(train$y[i])
```

```{r}
train <- train %>% mutate(value = 1)  %>% spread(y, value,  fill = 0 )
test <- test %>% mutate(value = 1)  %>% spread(y, value,  fill = 0 ) 
train$y = as.factor(load_label_file("train-labels-idx1-ubyte"))
test$y  = as.factor(load_label_file("t10k-labels-idx1-ubyte"))
```

```{r}
#layer_dense(units = 16, activation = "relu").
library(keras)
model <- keras_model_sequential() %>%
layer_dense(units = 16, activation = "relu", input_shape = c(784)) %>%
layer_dense(units = 16, activation = "relu") %>%
layer_dense(units = 1, activation = "sigmoid")

model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy"
)

val_indices <- 1:10000
x_val <- train[val_indices, 1:784]
partial_x_train <- train[-val_indices, 1:784]
y_val <- train[val_indices, 795]
partial_y_train <- train[-val_indices, 795]

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512
  #validation_data = list(x_val, y_val)
)
```


```{r}
fit = randomForest(y ~ .,data = train[1:1000,])
fit$confusion
test_pred = predict(fit,test)
mean(test_pred == test$y)
test_pred == test$y
which(test_pred != test$y)
incorrect <- (test_pred != test$y)
#for (i in which(incorrect)){
 # show_digit(test[i, ])
#}

```

```{r}
for(i in which(incorrect)[1:10]){
  show_digit(test[i, ])
  print(test_pred[i])
}
```



