---
title: "R4ds Exercises"
author: "Darin Stephenson"
date: "6/1/2021"
output:
  html_document:
    df_print: paged
  pdf_document: default
---


```{r setup, include=FALSE}
require("knitr")
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir=normalizePath("..")) #set working directory to the project directory
library(ggstance)
library(lvplot)
library(hexbin)
library(conflicted)
library(tidyverse)
conflict_prefer("select", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("filter", "dplyr")
```

```{r Chp.7, practice}
diamonds %>% 
  count(cut_width(carat, 0.5))
```

```{r}
smaller <- diamonds %>% 
  filter(carat < 3)
  
ggplot(data = smaller, mapping = aes(x = carat)) +
  geom_histogram(binwidth = 0.1)
```

```{r}
ggplot(data = smaller, mapping = aes(x = carat, colour = cut)) +
  geom_freqpoly(binwidth = 0.1)
```

```{r}
ggplot(data = smaller, mapping = aes(x = carat)) +
  geom_histogram(binwidth = 0.01)
```

```{r}
unusual <- diamonds %>% 
  filter(y < 3 | y > 20) %>% 
  select(price, x, y, z) %>%
  arrange(y)
unusual

usual <- diamonds %>%
  filter(y>3 & y<20) %>%
  select(price, x, y, z) %>%
  arrange(y)
usual

ggplot(usual)+
geom_histogram(mapping = aes(x = y), binwidth = 0.5) #histogram of data without unusual values
```

```{r}
priceExplore <- diamonds %>% 
  select(price, x, y, z, cut, carat, color) %>%
  arrange(y)
priceExplore

ggplot(data = smaller, mapping = aes(x = carat, y = price, color = color)) +
  geom_point() # compares carat and price, color sorts by the colors of the diamonds, exercise 2
```

```{r}
#replaces unusual values with NA
diamonds2 <- diamonds %>% 
  mutate(y = ifelse(y < 3 | y > 20, NA, y))
ggplot(data = diamonds2, mapping = aes(x = x, y = y)) + 
  geom_point(na.rm = TRUE)
#> Warning: Removed 9 rows containing missing values (geom_point).
```

```{r}
caratfilter <- diamonds %>%
  filter(carat == 0.99 | carat == 1) 

ggplot(data = caratfilter)+
  geom_histogram(mapping = aes(x = carat), binwidth = .01) #exercise 3
```

```{r}
nycflights13::flights %>% 
  mutate(
    cancelled = is.na(dep_time),
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + sched_min / 60
  ) %>% 
  ggplot(mapping = aes(sched_dep_time)) + 
    geom_freqpoly(mapping = aes(colour = cancelled), binwidth = 1/4)
```

```{r}
nycflights13::flights %>% 
  mutate(
    cancelled = is.na(dep_time),
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + sched_min / 60
  ) %>% 
  ggplot(mapping = aes(sched_dep_time)) + 
    geom_histogram(mapping = aes(colour = cancelled), binwidth = 1/4)
```

```{r}
nycflights13::flights %>% 
  mutate(
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + sched_min / 60
  ) %>% 
  ggplot(mapping = aes(sched_dep_time)) + 
    geom_histogram(mapping = aes(colour = is.na(dep_time)), binwidth = 1/4) 
```

```{r}
nycflights13::flights %>% 
  mutate(
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + sched_min / 60
  ) %>% 
  ggplot(mapping = aes(sched_dep_time)) + 
    geom_bar(mapping = aes(colour = is.na(dep_time)))
mean(flights, dep_time)  #Exercise 1
```

```{r}
mean(flights$dep_time, na.rm = TRUE)
```

```{r}
sum(flights$dep_time, na.rm = TRUE)  #Exercise 2
```

```{r}
ggplot(data = diamonds, mapping = aes(x = price)) + 
  geom_freqpoly(mapping = aes(colour = cut), binwidth = 500)
```

```{r}
ggplot(diamonds) + 
  geom_bar(mapping = aes(x = cut))
```

```{r}
ggplot(data = diamonds, mapping = aes(x = cut, y = price)) +
  geom_boxplot()
```

```{r}
nycflights13::flights %>% 
  mutate(
    cancelled = is.na(dep_time),
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + sched_min / 60
  ) %>% 
  ggplot() + 
    geom_boxplot(mapping = aes(y = sched_dep_time, x = cancelled)) #exercise 1
```

```{r}
#Testing carat vs. price, because most diamonds are sold based on carat
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point()
```

```{r}
ggplot(data = diamonds, mapping = aes(x = carat, y = price)) +
  geom_boxplot(mapping = aes(group = cut_width(carat, 0.1)), orientation = "x") #changing width to fit well according to carat
```

```{r}
diamonds %>%
  mutate(color = fct_rev(color)) %>%
  ggplot(aes(x=color, y=price)) +
  geom_boxplot() #color vs. price: small negative relationship
```

```{r}
diamonds %>%
  ggplot(aes(x=clarity, y=price)) +
  geom_boxplot() #clarity vs. price: still not as a strong relationship as carat
```

```{r}
diamonds %>%
  ggplot(aes(x=cut, y=carat)) +
  geom_boxplot() #interesting that a 5 carat diamond as a fair cut, but makes sense for being able to sell at a somewhat reasonable price
#**************** exercise 2
```


```{r}
ggplot(data = mpg) +
  geom_boxplot(mapping = aes(x = reorder(class, hwy, FUN = median), y = hwy)) +
  coord_flip()
```

```{r}
mpg %>%
  ggplot() +
  geom_boxploth(mapping = aes(y = reorder(class, hwy, FUN = median), x = hwy))
```

```{r}
mpg %>%
  ggplot() +
  geom_boxploth(mapping = aes(y = reorder(class, hwy, FUN = median), x = hwy), orientation = "y") #exercise 3
```

```{r}
diamonds %>%
  ggplot(aes(x = cut, y = price)) + 
  geom_lv() #is this like the spread of data? not really sure, doesn't have a ton of outlying points like the box plot though. 
#Exercise 4 **********
```

```{r}
#Start: 7.5.2 **********
ggplot(data = diamonds) +
  geom_count(mapping = aes(x = cut, y = color))
```

```{r}
diamonds %>%
  count(color, cut)
#Prints the table that shows how many diamonds are under each color/cut
```

```{r}
#Working with geom_tile
diamonds %>%
  count(color, cut) %>%
  ggplot(mapping = aes(x = color, y = cut)) +
  geom_tile(mapping = aes(fill = n))
```

```{r}
diamonds %>%
  count(color, cut) %>%
  group_by(color) %>%
  mutate(prop = n / sum(n)) %>%
  ggplot(mapping = aes(x = color, y = cut)) +
  geom_tile(mapping = aes(fill = prop))
```

```{r}
ggplot(data = diamonds) +
  geom_point(mapping = aes(x = carat, y = price))
```

```{r}
ggplot(data = diamonds) + 
  geom_point(mapping = aes(x = carat, y = price), alpha = 1 / 100) #adds transparency
```


```{r}
ggplot(data = diamonds) +
  geom_bin2d(mapping = aes(x = carat, y = price))

ggplot(data = diamonds) +
  geom_hex(mapping = aes(x = carat, y = price), bins=50)
```

```{r}
ggplot(data = diamonds, mapping = aes(x = carat, y = price)) + 
  geom_boxplot(mapping = aes(group = cut_width(carat, 0.1)))
```

```{r}
ggplot(data = diamonds, mapping = aes(x = carat, y = price)) + 
  geom_boxplot(mapping = aes(group = cut_number(carat, 20)))
```

```{r}
#7.6*********
library(modelr)

mod <- lm(log(price) ~ log(carat), data = diamonds)

diamonds2 <- diamonds %>% 
  add_residuals(mod) %>% 
  mutate(resid = exp(resid))

ggplot(data = diamonds2) + 
  geom_point(mapping = aes(x = carat, y = resid)) #removing the strong relationship between price and carat so we can explore the subtleties that remain
#Now, we can see the relationship between cut and price:
ggplot(data = diamonds2) + 
  geom_boxplot(mapping = aes(x = cut, y = resid))
#Result: relative to size, better quality diamonds (better cut) are more expensive -> Q: so "resid" is like "price"?? ******
```

ggplot(data = faithful, mapping = aes(x = eruptions))
^
ggplot(faithful, aes(eruptions))

```{r}
#ex:
ggplot(data = faithful, mapping = aes(x = eruptions)) + 
  geom_freqpoly(binwidth = 0.25)
ggplot(faithful, aes(eruptions)) + 
  geom_freqpoly(binwidth = 0.25)
#They do the same thing****
```
















